# Generated by Django 3.0.5 on 2020-06-25 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200524_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('upload', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profilepic',
            field=models.URLField(blank=True),
        ),
    ]
