# Generated by Django 3.0.5 on 2020-06-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200625_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(default=201, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
            preserve_default=False,
        ),
    ]
