# Generated by Django 3.0.5 on 2020-06-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_teacher'),
        ('administration', '0004_auto_20200625_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='course_id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='course_name',
            new_name='class_name',
        ),
    ]
