# Generated by Django 3.0.5 on 2020-06-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200625_2208'),
        ('administration', '0005_auto_20200625_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fees',
            new_name='Fee',
        ),
    ]
