# Generated by Django 3.0.5 on 2020-06-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200625_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
