# Generated by Django 3.0.5 on 2020-06-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200625_1654'),
        ('student', '0003_auto_20200625_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.Assignment')),
                ('answer', models.URLField()),
            ],
            bases=('teacher.assignment',),
        ),
    ]
