# Generated by Django 3.0.5 on 2020-06-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_assignmentanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentAnswer',
        ),
    ]
