# Generated by Django 3.0.5 on 2020-06-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200625_1654'),
        ('student', '0005_delete_assignmentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.URLField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Assignment')),
            ],
        ),
    ]
