# Generated by Django 3.0.5 on 2020-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='name',
            field=models.CharField(default=201851150, max_length=100),
            preserve_default=False,
        ),
    ]
